#python plot_gof_pvalues.py -i /data9/Users/HNL_public/SUS-24-014/Combine/CMSSW_14_1_0_pre4/src/DilepHN/GOF/ANv7_NewBinning_PR192_HNL_ULIDv2_FixCR3H_PruneZG_V3_Strict_15_Bin_RunSyst_Decorr_JetDecorr_PR188/Unblind/ --cmsExtra "Work in progress" 
#python plot_gof_pvalues.py -i /data9/Users/HNL_public/SUS-24-014/Combine/CMSSW_14_1_0_pre4/src/DilepHN/GOF/ANv7_NewBinning_PR192_HNL_ULIDv2_FixCR3H_PruneZG_V3_Strict_15_Bin_RunSyst_Decorr_JetDecorr_PR188/Unblind/ --logy --cmsExtra "Work in progress"

#python plot_gof_pvalues.py -i /data9/Users/HNL_public/SUS-24-014/Combine/CMSSW_14_1_0_pre4/src/DilepHN/GOF/ANv7_ConvUpdate_PR192_HNL_ULIDv2_NoLowDYMG_LowStatNeff5_V3_Strict_15_Bin_RunSyst_Decorr_JetDecorr_PR194/Unblind --cmsExtra "Work in progress" -o "ANv7_ConvUpdate_PR192_HNL_ULIDv2_NoLowDYMG_LowStatNeff5"
#python plot_gof_pvalues.py -i /data9/Users/HNL_public/SUS-24-014/Combine/CMSSW_14_1_0_pre4/src/DilepHN/GOF/ANv7_ConvUpdate_PR192_HNL_ULIDv2_NoLowDYMG_LowStatNeff5_V3_Strict_15_Bin_RunSyst_Decorr_JetDecorr_PR194/Unblind --logy --cmsExtra "Work in progress" -o "ANv7_ConvUpdate_PR192_HNL_ULIDv2_NoLowDYMG_LowStatNeff5"
#python plot_gof_pvalues.py -i /data9/Users/HNL_public/SUS-24-014/Combine/CMSSW_14_1_0_pre4/src/DilepHN/GOF/ANv7_ConvUpdate_PR192_HNL_ULIDv2_NoLowDYMG_LowStatNeff5_V3_Strict_15_Bin_RunSyst_Decorr_JetDecorr_PR194/Unblind --cmsExtra "Work in progress" -o "ANv7_ConvUpdate_PR192_HNL_ULIDv2_NoLowDYMG_LowStatNeff5" --region sr1
#python plot_gof_pvalues.py -i /data9/Users/HNL_public/SUS-24-014/Combine/CMSSW_14_1_0_pre4/src/DilepHN/GOF/ANv7_ConvUpdate_PR192_HNL_ULIDv2_NoLowDYMG_LowStatNeff5_V3_Strict_15_Bin_RunSyst_Decorr_JetDecorr_PR194/Unblind --logy --cmsExtra "Work in progress" -o "ANv7_ConvUpdate_PR192_HNL_ULIDv2_NoLowDYMG_LowStatNeff5" --region sr1
#python plot_gof_pvalues.py -i /data9/Users/HNL_public/SUS-24-014/Combine/CMSSW_14_1_0_pre4/src/DilepHN/GOF/ANv7_ConvUpdate_PR192_HNL_ULIDv2_NoLowDYMG_LowStatNeff5_V3_Strict_15_Bin_RunSyst_Decorr_JetDecorr_PR194/Unblind --cmsExtra "Work in progress" -o "ANv7_ConvUpdate_PR192_HNL_ULIDv2_NoLowDYMG_LowStatNeff5" --region sr2
#python plot_gof_pvalues.py -i /data9/Users/HNL_public/SUS-24-014/Combine/CMSSW_14_1_0_pre4/src/DilepHN/GOF/ANv7_ConvUpdate_PR192_HNL_ULIDv2_NoLowDYMG_LowStatNeff5_V3_Strict_15_Bin_RunSyst_Decorr_JetDecorr_PR194/Unblind --logy --cmsExtra "Work in progress" -o "ANv7_ConvUpdate_PR192_HNL_ULIDv2_NoLowDYMG_LowStatNeff5" --region sr2
#python plot_gof_pvalues.py -i /data9/Users/HNL_public/SUS-24-014/Combine/CMSSW_14_1_0_pre4/src/DilepHN/GOF/ANv7_ConvUpdate_PR192_HNL_ULIDv2_NoLowDYMG_LowStatNeff5_V3_Strict_15_Bin_RunSyst_Decorr_JetDecorr_PR194/Unblind --cmsExtra "Work in progress" -o "ANv7_ConvUpdate_PR192_HNL_ULIDv2_NoLowDYMG_LowStatNeff5" --region sr3
#python plot_gof_pvalues.py -i /data9/Users/HNL_public/SUS-24-014/Combine/CMSSW_14_1_0_pre4/src/DilepHN/GOF/ANv7_ConvUpdate_PR192_HNL_ULIDv2_NoLowDYMG_LowStatNeff5_V3_Strict_15_Bin_RunSyst_Decorr_JetDecorr_PR194/Unblind --logy --cmsExtra "Work in progress" -o "ANv7_ConvUpdate_PR192_HNL_ULIDv2_NoLowDYMG_LowStatNeff5" --region sr3
